packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/engines': true
  argon2: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  unrs-resolver: true

auditConfig:
  ignoreGhsas:
    - GHSA-ggr8-5vv4-36mx
